# -*- coding: utf-8 -*-
"""01_intro_opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-np4FYDgQ9d_aYNZ65aev-Qilo1c1sj
"""

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/sample.jpg")

cv2_imshow(img)

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)

small = cv2.resize(img,(300,300))

cv2_imshow(small)

crop = img[80:250,50:250]

cv2_imshow(crop)

img2 = img.copy()

cv2.rectangle(img2,(50,50),(200,200),(0,0,255),2)

cv2.circle(img2,(100,100),40,(0,255,0),2)

cv2.putText(img2,"This is Text on image",(50,300),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,0),2)

