# -*- coding: utf-8 -*-
"""02_basic_operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpq5UZYzgbxfHk-Y6cU7-jCAlF_UPpqo
"""

import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/sample.jpg")

if img is not None:
  cv2_imshow(img)

h,w = img.shape[:2]
center = (w// 2 , h// 2)

M = cv2.getRotationMatrix2D(center,180,1)

rotated = cv2.warpAffine(img,M,(w,h))

cv2_imshow(rotated)

flip1 = cv2.flip(img,1)
cv2_imshow(flip1)

flip0 = cv2.flip(img,0)
cv2_imshow(flip0)

flip_1 = cv2.flip(img,-1)
cv2_imshow(flip_1)

b,g,r = cv2.split(img)

cv2_imshow(b)

cv2_imshow(g)

cv2_imshow(r)

rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2_imshow(rgb)

blur = cv2.GaussianBlur(img,(9,9),0)

cv2_imshow(blur)

med = cv2.medianBlur(img,5)

cv2_imshow(med)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, th = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY)

cv2_imshow(th)

ad = cv2.adaptiveThreshold(gray,255,
                           cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                           cv2.THRESH_BINARY,11,2)

cv2_imshow(ad)

