# -*- coding: utf-8 -*-
"""03_filters_edges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKOqwvJM3f8OAo-4fnZr2ASjRhTMGDF1
"""

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/sample.jpg")

blurred = cv2.GaussianBlur(img,(5,5),0)

cv2_imshow(blurred)

canny = cv2.Canny(blurred,50,250)

cv2_imshow(canny)

sobalx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
cv2_imshow(sobalx)

sobaly = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
cv2_imshow(sobaly)

sobalx = cv2.convertScaleAbs(sobalx)
cv2_imshow(sobalx)

sobaly = cv2.convertScaleAbs(sobaly)
cv2_imshow(sobaly)

combo = cv2.bitwise_or(sobalx,sobaly)
cv2_imshow(combo)

